builder: scratch

archs: 
  - arm
  - amd64
  - arm64

args:
  version: "edge"
  mirror: "http://dl-cdn.alpinelinux.org/alpine"
  apk_arch: 
    arm: "armhf"
    arm64: "aarch64"
    amd64: "x86_64"
  qemu_arch: 
    arm: "arm"
    arm64: "aarch64"
    amd64: "x86_64"  

image: "fogger/alpine:{{.args.version}}"

build: 
  image: "{{.image}}-{{.arch}}"
  script:
    - |
      mkdir -p rootfs/usr/bin apk/sbin
      apkv=$(curl -sSL {{.args.mirror}}/{{.args.version}}/main/{{.args.apk_arch}}/APKINDEX.tar.gz | tar -Oxz | strings | grep '^P:apk-tools-static$' -A1 | tail -n1 | cut -d: -f2)
      curl -sSL {{.args.mirror}}/{{.args.version}}/main/{{.args.apk_arch}}/apk-tools-static-${apkv}.apk | tar -xz -C apk sbin/apk.static
      wget https://github.com/multiarch/qemu-user-static/releases/download/v2.6.0/x86_64_qemu-{{.args.qemu_arch}}-static.tar.gz
      tar -xzvf x86_64_qemu-{{.args.qemu_arch}}-static.tar.gz -C rootfs/usr/bin/
      apk/sbin/apk.static -X {{.args.mirror}}/{{.args.version}}/main -U --allow-untrusted -p rootfs --initdb add alpine-base
      printf '%s\n' {{.args.mirror}}/{{.args.version}}/main > rootfs/etc/apk/repositories
      tar --numeric-owner -C rootfs -c . | gzip > rootfs.tar.gz
      rm -rf rootfs apk x86_64_qemu-*-static.tar.gz
  dockerfile:
    from: "scratch"
    script:
      - "ADD rootfs.tar.gz /"

save:                                              
  output: "app-{{.arch}}.tar.gz"

push:
  manifest: true
  latest: false